### ISSUE TITLE
Unexpected files in a user's store - being restored in the wrong location

### ISSUE THREAD

**Issue by DRY411S** [belowaverage-org/SuperGrate#102]
**Describe the bug**
The creation of a user profile store includes files that do not belong to them.
In my case, this was files from a logical drive M:, which had been used on several different computers.
There are files on that M: drive that belong to users on a computer that is NOT the source, and those users do not exist on the source PC where I am building the store.
When this incorrect store is used to create the profile on a new PC, files are placed on the destination, but do not belong the user being migrated. Additionally, they are not restored in the correct location, instead they are stored at the root of the C: drive.

**To Reproduce**
1. Create a store on the source PC. Ensure that the source PC has access to files that belong to users that do not exist on the source PC. A way to do this is have an external disk mounted that has files belonging to users on another computer. (Or does SuperGrate recognise it as external and exclude it? In my case the disk was physically installed in the source, but had been used in other PCs)
2. Restore the store on the destination PC.
4. Browse the destination C: drive and note that there are folders and files now present that did not belong to the migrated user on the source PC. Additionally, on the source PC they were on the external drive, not the C: root.

**Expected behavior**
No rogue folders on the destination C: drive that have come from the source.

**Screenshots**
I can provide if required.

**Logs**
I can provide if required.

Please paste logs here in a code block.

**IMPORTANT**

To retrieve the logs, click "File", the select "Save log..." Copy the contents of the log file and paste it here.
Refrain from copying and pasting the log from the console since it does not output verbose information.

```

**Additional context**
Source Win10 Pro destination Win 11 Pro, both 64 bit.
I have tried this with an M: drive created on the destination, but the files still get restored to destination C:, whether or not the destination includes an M: drive. (I don't understand why the files are included in the profile in the first place.)

**Comment by DRY411S** [comment]
Further analysis on this shows me that the folders that have been included in the store but are not in the %USERPROFILE% path, and are on other logical drives, in fact belong to  a 'ghost' user that has no login id on the source PC. The user on the source is shown in File Explorer as 'S-1-5-21- etc'

Clearly I have some corruptions/inconsistencies, but the response to these by Supergrate does not seem appropriate.

**Comment by krisdb2009** [comment]
Can you share your SuperGrate.xml file? Feel free to remove anything sensitive.
