### ISSUE TITLE
This looks awesome, but VirusTotal flags it as Malicious

### ISSUE THREAD

**Issue by jacobhweeks** [belowaverage-org/SuperGrate#110]
**Describe the bug**
VirusTotal flags the exe as Malicious.

**To Reproduce**
1. Go to VirusTotal.com and upload the .exe file
2. See the results

**Expected behavior**
No Malicious flags

**Screenshots**
![image](https://github.com/belowaverage-org/SuperGrate/assets/6288324/8a768817-0c03-4c1b-8ef6-ab87d3242826)

**Additional context**
I want to use this tool because USMT is very complicated via the command line, But I (and many other security-minded professionals) can't use this in good conscience.

**Comment by krisdb2009** [comment]
Unfortunately, there isn't a whole lot I can do besides acquiring a very expensive "code signing certificate." I encourage anyone to submit these builds to their AV vendors as a false positive to help alleviate this and help build a good reputation for the software.

In regard to your security team / co-workers. You can always review the source code yourself and build the binary on your machine, I have a guide on how to do this on the documentation page for this project.

**Comment by jacobhweeks** [comment]
The flags that I saw were indicating a directory being used that is common
for malware. But that may have just been a comment.

Respectfully,

Jacob H. Weeks
