### ISSUE TITLE
Could not generate a working directory for USMT at: C:\SuperGrate. The folder already exists.

### ISSUE THREAD

**Issue by Ranger2000** [belowaverage-org/SuperGrate#126]
Created the Folder C:\SuperGrate put in the SuperGrate.exe.
Start App -> Accept UAC -> select local Computer -> select local User - > click "start" and got error:
"Could not generate a working directory for USMT at: C:\SuperGrate. The folder already exists."

At the beginning the Folder USMT is not there, but after the first start the USMT package was decompressed sucsessfull.
See Screenshot below

Restartet the Computer an tested it again, but got the same error 😔

See log:
[INFO]<16:09:12> Generating SuperGrate.xml...
[SUCCESS]<16:09:12> Done.
[SUCCESS]<16:09:12> SuperGrate.xml loaded.
[SUCCESS]<16:09:13> Welcome to Super Grate! v1.4.4.0
[INFO]<16:09:13> Enter some information to get started!
[INFO]<16:09:15> Listing users from DESKTOP-N9BN83U...
[VERBOSE]<16:09:15> Found user DESKTOP-N9BN83U\grzadmin.
[VERBOSE]<16:09:15> Found user NT-AUTORITÄT\Netzwerkdienst.
[VERBOSE]<16:09:15> Skipped S-1-5-20 NT-AUTORITÄT\Netzwerkdienst.
[VERBOSE]<16:09:15> Found user NT-AUTORITÄT\Lokaler Dienst.
[VERBOSE]<16:09:15> Skipped S-1-5-19 NT-AUTORITÄT\Lokaler Dienst.
[VERBOSE]<16:09:15> Found user NT-AUTORITÄT\SYSTEM.
[VERBOSE]<16:09:15> Skipped S-1-5-18 NT-AUTORITÄT\SYSTEM.
[SUCCESS]<16:09:15> Users listed successfully from DESKTOP-N9BN83U.
[INFO]<16:09:16> Gathering user properties...
[VERBOSE]<16:09:16> Found user DESKTOP-N9BN83U\grzadmin.
[INFO]<16:09:16> Calculating profile size for DESKTOP-N9BN83U\grzadmin...
[SUCCESS]<16:09:17> Done.
[INFO]<16:09:20> Gathering OS architecture on DESKTOP-N9BN83U...
[INFO]<16:09:20> The OS architecture on DESKTOP-N9BN83U is X64.
[INFO]<16:09:20> Uploading USMT to DESKTOP-N9BN83U...
[WARNING]<16:09:20> Failed to find USMT folder at .\USMT\X64.
[INFO]<16:09:20> Downloading USMT X64 from the web...
[INFO]<16:09:21> Decompressing USMT...
[INFO]<16:09:21> Cleaning up USMT...
[ERROR]<16:09:21> Could not generate a working directory for USMT at: C:\SuperGrate. The folder already exists.
[INFO]<16:09:21> Done.
[INFO]<16:09:36> Writing log to .\LOGS...

<img width="450" alt="2024-11-24_16-09-34_9AX" src="https://github.com/user-attachments/assets/aad45996-458e-41f5-8579-3f56048e9663">

<img width="666" alt="2024-11-24_16-19-36_TAh" src="https://github.com/user-attachments/assets/0226c03e-867b-4b14-9087-3fba001ba904">

**Comment by krisdb2009** [comment]
Super Grate uses C:\SuperGrate by default as a temp working directory. The reason it threw the error is because it wants to use that path temporary and then clean it up after it runs a cycle.

To fix this, manually remove C:\SuperGrate and try to run a backup again.

If you are dead set on using C:\SuperGrate as a home location for the SuperGrate.exe, then open Super Grate settings and change the "SuperGratePayloadPath" parameter to "C:\SuperGrateTemp"

Hope this helps!

**Comment by Ranger2000** [comment]
Thank you for your patience in clearing up my misunderstanding.
I used a different folder or, as you said, specified a different temp directory in the settings, and it works wonderfully.
Thank you for the great program and your tireless work 🤗

**Comment by krisdb2009** [comment]
I really appreciate that. Thank you!
