### ISSUE TITLE
Amazing Project

### ISSUE THREAD

**Issue by cmartinezone** [belowaverage-org/SuperGrate#32]
I want to thank you for this amazing project.
I am looking forward to downgrading the .NET framework to 4.5  to make this tool compatible with Windows WinPE and use USMT Offline migration, I have some experience with C#.
https://docs.microsoft.com/en-us/windows/deployment/usmt/offline-migration-reference

Thanks,
Carlos

**Comment by krisdb2009** [comment]
You shouldn't need to downgrade the .NET version for WinPE; however, there will need to be a lot of changes done to the source to make Super Grate work in WinPE. All processes are currently invoked using remote WMI calls which is not available in WinPE.
I actually plan on adding code to detect weather or not Super Grate is invoking a process locally and then decide if a process should be invoked over WMI or normally using the .NET Process API. This should make implementing Super Grate for WinPE much easier.

**Comment by krisdb2009** [comment]
I am curious why you want to run Super Grate in WinPE.
Microsoft's Deployment Toolkit has USMT built in already.

**Comment by cmartinezone** [comment]
Thank you for replaying. WinPE does support WMI, the package needs to be added to the Image.
I have one project, I have been working focus on creating custom WinPE Easily.
https://github.com/cmartinezone/WinPEBuilder

The NetFx WinPE Packages adds support for .NET, but according to the documentation is .NET 4.5


I do want to run Super Grate to capture the user profiles after, I unlock a BitLocker Encrypted Drive, instead of waiting for decrypting the whole drive to make the backup, I can capture the users' states offline, since USMT supports offline migration.

Thanks,
Carlos

**Comment by cmartinezone** [comment]
can you, please re-do the assignment, please. I removed it by mistake.

**Comment by krisdb2009** [comment]
Thanks for sharing, I will try it out myself in WinPE.
