### ISSUE TITLE
Add support for user-renaming.

### ISSUE THREAD

**Issue by krisdb2009** [belowaverage-org/SuperGrate#41]
Add support for the below in some sort of fashion.

![image](https://user-images.githubusercontent.com/8226974/73230730-3de59f00-414c-11ea-80a6-1e77c6e8f1e2.png)

**Comment by supajo** [comment]
Hi krisdb2009, any idea when your new feature will be available?
Greetings supajo
PS: Thanks for your great tool

**Comment by krisdb2009** [comment]
@supajo 

Not sure.

I have not given it much thought.
Would this be a useful feature? If so, how would you utilize it?

Thanks,

Dylan

**Comment by supajo** [comment]
It would be very useful! I would use it in a cross domain migration scenario.
Sure USMT as a commandline is available but a gui is so much nicer :-)

**Comment by krisdb2009** [comment]
Noted. I will keep this request open since it clearly has merit.

**Comment by krisdb2009** [comment]
Support finished for this in cb80857dec0b6fed1fbd8661fadb7bb6b43b530b.
