### ISSUE TITLE
Typo in Classes/USMT.cs

### ISSUE THREAD

**Issue by gatesps** [belowaverage-org/SuperGrate#47]
Lines 35 and 39 both read `if(DetectedArch == Misc.OSArchitecture.X64)`, meaning that USMTPath will not be set if the machine is 32-bit.

**Comment by krisdb2009** [comment]
Great catch, come to think of it, I don't think I have ever tested SG on a x86 based PC.

https://github.com/belowaverage-org/SuperGrate/blob/b58d947f77bb87119135386da0f7b40c222fc6ff/SuperGrate/Classes/USMT.cs#L31
