### ISSUE TITLE
Allowing direct restore instead of downloading the file and restore.

### ISSUE THREAD

**Issue by jedduff** [belowaverage-org/SuperGrate#54]
Hi!

Thanks for the software, it's very handy! 

I have a situation where the migration file is way too big for the destination computer hard disk

Ex : Migration file is 230GB (compressed), computer hard drive is 480GB. So I need at least 500GB in free space (scratch folder + profile), so the hard disk don't have enough free space to handle the mig file + profile.

I tried to found a way to not download the file, but instead restore using the mig file directly. But I don't see any way to do it. I use loadscan manually, but the mig file is not in the good format.

**Comment by krisdb2009** [comment]
Hi Jed,

There is a setting in Super Grate that lets you change the location of the temp scratch space. Try changing the setting to point to the path of an external HDD or something like that.

![image](https://user-images.githubusercontent.com/8226974/98392797-6a591080-2026-11eb-8fb4-36d70ff82551.png)

Let me know if that helps!
