### ISSUE TITLE
Error Running try to get users Profile Names

### ISSUE THREAD

**Issue by ArccRustyf** [belowaverage-org/SuperGrate#61]
**Describe the bug**

**To Reproduce**
1. Go to 'Source Computer, Select Computer Name.'
2. Click on 'List Source'

2:43:53 PM> Config loaded!
2:43:53 PM> Welcome to Super Grate! v1.3.0.0
2:43:53 PM> Enter some information to get started!
2:43:59 PM> Getting list of users on: ARCC001402...
2:43:59 PM> Could not resolve as an SID via WMI!
2:43:59 PM> Object reference not set to an instance of an object.
2:43:59 PM> Failed to get a list of users. Please make sure that the specified host is valid and online and that you are an administrator of: ARCC001402

**Expected behavior**

**Screenshots**

**Logs**
```
Please paste logs here in a code block.

**IMPORTANT**

To retrieve the logs, click "File", the select "Save log..." Copy the contents of the log file and paste it here.
Refrain from copying and pasting the log from the console since it does not output verbose information.

```

**Additional context**

**Comment by ArccRustyf** [comment]
Fixed now it was not the software. I was a corrupt register entry causing the issue.

**Comment by MiketheMaker18** [comment]
> Fixed now it was not the software. I was a corrupt register entry causing the issue.

Do you know which registry entry is causing this? Receiving this error now after no changes (to supergrate).

Thanks!
