### ISSUE TITLE
CLI to pass hostname

### ISSUE THREAD

**Issue by MiketheMaker18** [belowaverage-org/SuperGrate#62]
**Describe the solution you'd like**
Would love to use this to use command line to pass the hostname to backup. We utilize software that can read out a hostname variable so our techs could essentially right click a computer in our inventory software and begin a scanstate with the hostname already filled in.

**Comment by krisdb2009** [comment]
That's a great idea! I will to work on that.

**Comment by MiketheMaker18** [comment]
> That's a great idea! I will to work on that.

Awesome. Looking forward to it. Thanks a ton for taking this into consideration!

**Comment by krisdb2009** [comment]
@MiketheMaker18 

You can access this new switch like this:

`SuperGrate.exe /SourceComputer:COMPUTERNAME /TabView:Source`
