### ISSUE TITLE
Add Localization (HideBuildInAccounts not working)

### ISSUE THREAD

**Issue by Manschk3rl** [belowaverage-org/SuperGrate#67]
**Describe the bug**
If you have set your operating system to german, the setting "HideBuildInAccounts" does not work.
it shows entries like "NT-AUTHORITÄT\SYSTEM" (which is german for "NT-AUTHORITY\SYSTEM")

**To Reproduce**
1. Set your OS language to german.
2. Start SuperGrate.
3. Under "Settings" set "HideBuildInAccounts" on "true".
4. "Source Computer" > local machine
5. "List Source"
6. See the error

**Expected behavior**
"NT-xxx" entries should not appear in the list.

**Screenshots**
![1](https://user-images.githubusercontent.com/4741314/204777918-6279badd-d58d-4a4c-88b1-f109962d1b65.png)
![2](https://user-images.githubusercontent.com/4741314/204777933-03f56653-a5a3-4f5f-96d2-45c886f25fb7.png)

**Logs**
`[SUCCESS]<11:49:53> Config loaded!
[SUCCESS]<11:49:53> Welcome to Super Grate! v1.3.5.0
[INFO]<11:49:53> Enter some information to get started!
[INFO]<11:49:59> Getting list of users on: ZE999-WIN11...
[VERBOSE]<11:49:59> Found: ZE999-Win11\test
[WARNING]<11:49:59> Could not resolve as an SID via WMI!
[VERBOSE]<11:49:59> Found: S-1-5-21-85594344-4232975197-2231365188-1002
[VERBOSE]<11:49:59> Found: ZE999-Win11\Admin
[VERBOSE]<11:49:59> Found: NT-AUTORITÄT\Netzwerkdienst
[VERBOSE]<11:49:59> Found: NT-AUTORITÄT\Lokaler Dienst
[VERBOSE]<11:49:59> Found: NT-AUTORITÄT\SYSTEM
[SUCCESS]<11:49:59> Users listed successfully.
[INFO]<11:55:00> Writing log to: C:\Users\Admin\Desktop\SuperGrate_30.11.2022_11-54-57.log...`

**Additional context**
Im not a programmer but i guess its because the program is searching for "NT AUTHORITY". Found in "SuperGrate/Classes/Misc.cs" line 107 `if (bool.TryParse(Config.Settings["HideBuiltInAccounts"], out bool setting) && setting && (**user.Contains("NT AUTHORITY")** || **user.Contains("NT SERVICE")**))`

**Comment by krisdb2009** [comment]
Thanks for the report, it sounds like I am going to need to localize Super Grate with different languages.
That is a big task so might take me a few weeks to build in localization. I will likely need help from you with translating to German as well if you are up for it.

**Comment by krisdb2009** [comment]
That will work for now, mind sending a pull request?

**Comment by Manschk3rl** [comment]
Done.
But sure im up for the "Add Localization" projekt if you need help with german :)
