### ISSUE TITLE
Trojan horse in binary SuperGrate\SuperGrateUpdates\SuperUpdate.exe

### ISSUE THREAD

**Issue by kris877** [belowaverage-org/SuperGrate#70]
Hi All, 
I've cloned repository locally and my antyvirus system reported that in binary SuperGrate\SuperGrateUpdates\SuperUpdate.exe is infected with trojan Artemis!E2D6755046F3 .
Could you check anverify if it's true ?

Regards
Kris
![Zrzut ekranu 2022-12-20 124737](https://user-images.githubusercontent.com/71496213/208660264-30e18a85-80ef-4f24-b9f7-ed1131e61617.png)

**Comment by kris877** [comment]
Same problem with Kaspersky Antivirus, it reports HEUR:Trojan.MSIL.Alien.gen

**Comment by krisdb2009** [comment]
There is no virus in that file, but I removed the directory in the repo anyway since it is not needed anymore.
