### ISSUE TITLE
Add Fluent Design for W10 and W11

### ISSUE THREAD

**Issue by kronuschan** [belowaverage-org/SuperGrate#71]
**Is your feature request related to a problem? Please describe.**
The program works amazingly, but looks a bit out of place in Windows 10's and Windows 11's new Fluent Design language.

**Describe the solution you'd like**
Would it be possible to update the design language to be more in line with the newer design languages that were introduced?

**Describe alternatives you've considered**
None

**Additional context**
Acrylic would work under Windows 10 and Windows 11, but perhaps using Acrylic under 10 and Mica/Tabbed under 11 would work? Same with Segoe MDL icons under 10 and Segoe Fluent Icons under 11?

**Comment by krisdb2009** [comment]
Super Launcher already is using Fluent Design with Acrylic, it is just lacking the blur effect.
Are you asking for the blur effect to be implemented?

![image](https://user-images.githubusercontent.com/8226974/212860819-8b7a659f-34cb-46e8-a1a9-537f14aaa5c1.png)

**Comment by krisdb2009** [comment]
I probbably won't be able to mimick fluent design 100%, but here are my efforts so far:

![image](https://github.com/belowaverage-org/SuperGrate/assets/8226974/86944a1a-da23-4da5-af4a-2b7480be7105)

**Comment by krisdb2009** [comment]
Finished in 749a6a0b
