### ISSUE TITLE
Le fichier C:/SuperGrate/usmt/usmt.mig est introuvable 

### ISSUE THREAD

**Issue by ZOKOB** [belowaverage-org/SuperGrate#72]
Bonjour j'ai mis a jour la dernière version de supergrate et je ne peux plus faire de migration il ne trouve plus le fichier C:/SuperGrate/usmt/usmt.mig
J'ai testé avec d'ancienne version et en renitialisant ma configuration cela ne change rien.

Savez vous comment résoudre ce problème s'il vous plaît ?

En vous souhaitant une agréable journée 
Cordialement Rémy

**Comment by krisdb2009** [comment]
Remy,

Can you export the log and attach it here?

![image](https://user-images.githubusercontent.com/8226974/213722213-b4df924d-ce89-4077-9ffc-6266a1074877.png)

**Comment by maidmeow4** [comment]
Hi, I'm having the same issue on Windows server 2022 standard, here is the log file.

[SuperGrate_2023-5-16_16-07-09.log](https://github.com/belowaverage-org/SuperGrate/files/11485523/SuperGrate_2023-5-16_16-07-09.log)

**Comment by maidmeow4** [comment]
@krisdb2009 
Hi, I'm having the same issue on a Windows server 2022 standard, here is the log attached.

[SuperGrate_2023-5-16_16-07-09.log](https://github.com/belowaverage-org/SuperGrate/files/11485529/SuperGrate_2023-5-16_16-07-09.log)

**Comment by krisdb2009** [comment]
Good afternoon @maidmeow4, USMT is not supported on Windows Servers.

```﻿2023-05-16 16:07:02, Error                 [0x000000] Server Operating systems are not supported.[gle=0x000000cb]```
