### ISSUE TITLE
Keep getting "Uploading USMT to: ##### followed by The network name cannot be found.

### ISSUE THREAD

**Issue by ChrisFromIT** [belowaverage-org/SuperGrate#75]
**Describe the bug**

Hi 
I am starting on the process of migrating users from a Windows 10 to W11 environment and thought I would try using your tool.  Unfortunately, I am getting the error "The network name cannot be found."  "Error uploading USMT to: 8TB17D3"

SuperGrate is able to locate the computer, and identify the users (local and Domain) - it will even do the Size Calculations on the selected users (All domain) but then this error occurs.

I attached a screen shot of the error.

All drives are shared to Everyone R/W (for testing)

**To Reproduce**
Do what I said above.

**Expected behavior**
I expected the tool to copy the USMT to the network computer, run scanstate, copy USMT to the new computer and run loadstate.

**Screenshots**

![image](https://user-images.githubusercontent.com/129553783/229226359-1b3668b0-e26a-4472-a85e-349963ab35eb.png)

**Logs**
```


**IMPORTANT**

To retrieve the logs, click "File", the select "Save log..." Copy the contents of the log file and paste it here.
Refrain from copying and pasting the log from the console since it does not output verbose information.

[SUCCESS]<2:29:17 PM> Config loaded!
[SUCCESS]<2:29:17 PM> Welcome to Super Grate! v1.3.5.1
[INFO]<2:29:17 PM> Enter some information to get started!
[INFO]<2:29:21 PM> Getting list of users on: 8TB17D3...
[VERBOSE]<2:29:21 PM> Found: WICHE_NET\username
[VERBOSE]<2:29:21 PM> Found: 8TB17D3\Administrator
[VERBOSE]<2:29:21 PM> Found: NT AUTHORITY\NETWORK SERVICE
[VERBOSE]<2:29:21 PM> Skipped: S-1-5-20: NT AUTHORITY\NETWORK SERVICE.
[VERBOSE]<2:29:21 PM> Found: NT AUTHORITY\LOCAL SERVICE
[VERBOSE]<2:29:21 PM> Skipped: S-1-5-19: NT AUTHORITY\LOCAL SERVICE.
[VERBOSE]<2:29:21 PM> Found: NT AUTHORITY\SYSTEM
[VERBOSE]<2:29:21 PM> Skipped: S-1-5-18: NT AUTHORITY\SYSTEM.
[SUCCESS]<2:29:21 PM> Users listed successfully.
[INFO]<2:29:23 PM> Retrieving user properties...
[VERBOSE]<2:29:23 PM> Found: WICHE_NET\username
[INFO]<2:29:23 PM> Calculating profile size for: WICHE_NET\username...
[WARNING]<2:29:25 PM> Canceling current task...
[INFO]<2:29:25 PM> Canceled.
[INFO]<2:29:27 PM> Reading OS Architecture...
[INFO]<2:29:27 PM> OS Architecture is: X64.
[INFO]<2:29:27 PM> Uploading USMT to: 8TB17D3
[ERROR]<2:29:27 PM> The network name cannot be found.
[VERBOSE]<2:29:27 PM> ERROR
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at SuperGrate.IO.FileOperations.CopyFolder(String Source, String Destination)
   at SuperGrate.USMT.<>c.<<CopyUSMT>b__13_0>d.MoveNext()
[ERROR]<2:29:27 PM> Error uploading USMT to: 8TB17D3
[INFO]<2:29:27 PM> Done.
[INFO]<2:29:31 PM> Writing log to: .\LOGS...


```

**Additional context**

Added the XML File:

<?xml version="1.0" encoding="utf-8"?>
<SuperGrate>
  
  <USMTPathX64>D:\SuperGrate\USMT5</USMTPathX64>
  <USMTPathX86>F:\DeploymentShare\Tools\x86\USMT5</USMTPathX86>
  
  <SuperGratePayloadPath>D:\SuperGrate</SuperGratePayloadPath>
  
  <MigrationStorePath>D:\SuperGrate\SGUser_Store</MigrationStorePath>
  
  <ScanStateParameters>/config:Config.xml /i:ExcludeDrives_D_to_Z.xml /i:ExcludeSystemFolders.xml /i:ExcludeOneDriveRedirFolders.xml /i:MigApp.xml /i:MigUser.xml /i:Win10.xml /i:Win11.xml /i:custom.xml /c /r:3 /o</ScanStateParameters>
  <LoadStateParameters>/config:Config.xml /i:ExcludeDrives_D_to_Z.xml /i:ExcludeSystemFolders.xml /i:ExcludeOneDriveRedirFolders.xml /i:MigApp.xml /i:MigUser.xml /i:Win10.xml /i:Win11.xml /i:custom.xml  /c /r:3 /lac /lae</LoadStateParameters>
  
  <AutoDeleteFromStore>false</AutoDeleteFromStore>
  
  <AutoDeleteFromSource>false</AutoDeleteFromSource>
  
  <HideBuiltInAccounts>true</HideBuiltInAccounts>
  
  <HideUnknownSIDs>false</HideUnknownSIDs>
  
  <DumpLogHereOnExit>.\LOGS</DumpLogHereOnExit>
  
  <ULSourceColumns>0,3,9</ULSourceColumns>
  <ULStoreColumns>0,1,5,6,4</ULStoreColumns>
  
  <ULViewMode>1</ULViewMode>
  
  <SourceComputer>8TB17D3</SourceComputer>
  
  <DestinationComputer></DestinationComputer>
  
  <TabView>None</TabView>
  
  <SecurityProtocol>Tls12</SecurityProtocol>
</SuperGrate>

**Comment by krisdb2009** [comment]
Does the client's PC have a C$ share enabled?

![image](https://user-images.githubusercontent.com/8226974/229258314-028ae89f-26d4-4d4d-9241-c47b8df440e5.png)

**Comment by ChrisFromIT** [comment]
Hi @Krisdb2009 - When you ask about the Client - do you mean the one I am copying from, or to?  Either way, it would not be likely to have the C$ share enabled since that would open up that laptop to anyone on the network.  If the person running the program has Admin rights, can't they enable the share if needed?  Would it need to be shared R/O - or R/W?   I can try that if you think it will help...

**Comment by ChrisFromIT** [comment]
Hi @krisdb2009 - thanks for the response - I just looked at the shares on all of our systems and C$ is shared "for administrative purposes".  I thought it was strange that the system is able to scan and provide the size of the info to be copied - and the users on that device (it was a long term loaner), but it can't find it when the initial Copy of USMT is being done... 
Chris

**Comment by ChrisFromIT** [comment]
Hi - I was able to link and create a drive without any issues.

**Comment by krisdb2009** [comment]
Is "8TB17D3" really the PC name being used? I would like to try on my own PC with the same name to try to re-produce.

**Comment by ChrisFromIT** [comment]
Yes  it is the name - we use the Dell Service Tag as the naming convention for the systems.  
It failed on others also - JMRZJR2, C7M6KR2  are a couple more of them.

**Comment by ChrisFromIT** [comment]
I should also mention that these are all domain connected devices, they are
named   WICHE_NET\name on the domain Wiche.edu.  If you just ping the name
though, you get a response so I don't think that matters.  I am able to
connect to, for example,  8TB1TD3\C$  directly with no password needed -
and I was able to create a folder, and a file on that machine.
I appreciate your help with this...
Chris

**Comment by krisdb2009** [comment]
Can you upload a copy of your SuperGrate.xml again? It didn't come through correctly in the initial post.

**Comment by krisdb2009** [comment]
In particular, I am interested in what "SuperGratePayloadPath" is set to.

**Comment by ChrisFromIT** [comment]
Hi - Sorry for the delay - 
<SuperGrate>
  
  <USMTPathX64>D:\SuperGrate\USMT5</USMTPathX64>
  <USMTPathX86>F:\DeploymentShare\Tools\x86\USMT5</USMTPathX86>
  
  <SuperGratePayloadPath>D:\SuperGrate</SuperGratePayloadPath>
  
  <MigrationStorePath>D:\SuperGrate\SGUser_Store</MigrationStorePath>
  
  <ScanStateParameters>/config:Config.xml /i:ExcludeDrives_D_to_Z.xml /i:ExcludeSystemFolders.xml /i:ExcludeOneDriveRedirFolders.xml /i:MigApp.xml /i:MigUser.xml /i:Win10.xml /i:Win11.xml /i:custom.xml /c /r:3 /o</ScanStateParameters>
  <LoadStateParameters>/config:Config.xml /i:ExcludeDrives_D_to_Z.xml /i:ExcludeSystemFolders.xml /i:ExcludeOneDriveRedirFolders.xml /i:MigApp.xml /i:MigUser.xml /i:Win10.xml /i:Win11.xml /i:custom.xml  /c /r:3 /lac /lae</LoadStateParameters>
  
  <AutoDeleteFromStore>false</AutoDeleteFromStore>
  
  <AutoDeleteFromSource>false</AutoDeleteFromSource>
  
  <HideBuiltInAccounts>true</HideBuiltInAccounts>
  
  <HideUnknownSIDs>false</HideUnknownSIDs>
  
  <DumpLogHereOnExit>.\LOGS</DumpLogHereOnExit>
  
  <ULSourceColumns>0,3,9</ULSourceColumns>
  <ULStoreColumns>0,1,5,6,4</ULStoreColumns>
  
  <ULViewMode>1</ULViewMode>
  
  <SourceComputer></SourceComputer>
  
  <DestinationComputer></DestinationComputer>
  
  <TabView>None</TabView>
  
  <SecurityProtocol>Tls12</SecurityProtocol>
</SuperGrate>

**Comment by ChrisFromIT** [comment]
Hey - Sorry for the delay - and thanks for looking at this again:


[SuperGrate.txt](https://github.com/belowaverage-org/SuperGrate/files/11149562/SuperGrate.txt)

**Comment by ChrisFromIT** [comment]
I did a bit more digging and thought that this error was coming because I am RDP's into the Server that I'm running it on - -but I tried by logging in directly and I am not getting any different results.  It took me a bit to realize that the "Payload" is the location where SuperGrate is COPYING the data to on the remote machine - yes, the C$ drive makes more sense in this case.  I also checked the RPC Services, including DCOM to make sure it is running - it is.

**Comment by krisdb2009** [comment]
Yea I was about to say, I'm guessing you set `<SuperGratePayloadPath>D:\SuperGrate</SuperGratePayloadPath>` back to C:\SuperGrate ?

Did it resolve your issue?

**Comment by ChrisFromIT** [comment]
HI Dylan - It *almost* did... I added the Verbose Log from what happened
next - it was able to copy the files over, then it said it could not
connect.  I added some more info in the Github space for you.  I tried
moving the USMT out of the SuperGrate folder - it copied, but then could
not connect.  I killed the task before it was done copying and it did
actually do the copy now - but still no connect.  Let me know if you need
more info - I'm a programmer also so I can do whatever you need.
Chris

**Comment by ChrisFromIT** [comment]
Yes it does...

On 3/31/2023 7:09:08 PM, Dylan Bickerstaff ***@***.***> wrote:
Does the client's PC have a C$ share enabled?
[image] [https://user-images.githubusercontent.com/8226974/229258314-028ae89f-26d4-4d4d-9241-c47b8df440e5.png]

**Comment by krisdb2009** [comment]
So that new error you are getting might be because the remote registry service is not running on your client PCs.
You can push to enable via GPO. I want to remove this requirement (I honestly thought I did already) and use WMI to get the remote process list.

**Comment by ChrisFromIT** [comment]
I'll take a look at that ... thanks!  I ended up reverting to a PowerShell program that did the same thing but I would like to use this tool - it is a great option.

PS: I sent you a 6-pack for the help ..

**Comment by krisdb2009** [comment]
Oh wow thank you!
