### ISSUE TITLE
Detect Chip Architecture 

### ISSUE THREAD

**Issue by ds33d** [belowaverage-org/SuperGrate#8]
When running SuperGrate with 32-bit against a 64-bit system, an error is given "32-bit process on a  64-bit system is not supported". Please add feature to detect if 32-bit of 64-bit version of USMT is being used.

**Comment by krisdb2009** [comment]
Instead of programming this functionality in, I decided to just make two builds of Super Grate, a x64 & x86, and you will just need to have two instances with separate USMT folders with both builds.

**Comment by krisdb2009** [comment]
Continuing this feature.
